test=document_fix

diff --git a/.github/workflows/Coverage.yml b/.github/workflows/Coverage.yml
--- a/.github/workflows/Coverage.yml
+++ b/.github/workflows/Coverage.yml
@@ -43,213 +43,213 @@ jobs:
       bos_dir: Paddle-coverage
       task: coverage
 
-  build:
-    name: Coverage build
-    needs: [clone, build-docker]
-    if: needs.clone.outputs.can-skip != 'true'
-    runs-on:
-      group: GZ_BD-CPU
-    outputs:
-      can-skip: ${{ steps.check-bypass.outputs.can-skip }}
+  # build:
+  #   name: Coverage build
+  #   needs: [clone, build-docker]
+  #   if: needs.clone.outputs.can-skip != 'true'
+  #   runs-on:
+  #     group: GZ_BD-CPU
+  #   outputs:
+  #     can-skip: ${{ steps.check-bypass.outputs.can-skip }}
 
-    steps:
-      - name: Check docker image and run container
-        env:
-          CACHE_DIR: "/root/.cache/coverage"
-          CCACHE_DIR: "/root/.ccache/coverage"
-          FLAGS_fraction_of_gpu_memory_to_use: 0.15
-          CTEST_PARALLEL_LEVEL: 2
-          WITH_GPU: "ON"
-          CUDA_ARCH_NAME: Volta
-          WITH_AVX: "ON"
-          WITH_COVERAGE: "ON"
-          COVERALLS_UPLOAD: "ON"
-          PADDLE_VERSION: 0.0.0
-          CUDA_VISIBLE_DEVICES: 0,1
-          WITH_DISTRIBUTE: "ON"
-          PRECISION_TEST: "ON"
-          WITH_PIP_CUDA_LIBRARIES: "OFF"
-          WITH_FLAGCX: "ON"
-          LITE_GIT_TAG: develop
-          WITH_UNITY_BUILD: "ON"
-          PY_VERSION: 3.9
-          WITH_SHARED_PHI: "ON"
-          WITH_CINN: "ON"
-          INFERENCE_DEMO_INSTALL_DIR: /root/.cache/coverage
-          CCACHE_MAXSIZE: 200G
-          CCACHE_LIMIT_MULTIPLE: 0.8
-          ON_INFER: "ON"
-          PADDLE_CUDA_INSTALL_REQUIREMENTS: "ON"
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          UT_RUN_TYPE_SETTING: WITHOUT_HYBRID
-        run: |
-          container_name=${TASK}-build-$(date +%Y%m%d-%H%M%S)
-          echo "container_name=${container_name}" >> ${{ github.env }}
-          docker_image=${{ needs.build-docker.outputs.docker_coverage_image }}
-          docker run -d -t --name ${container_name} \
-            -v "/home/data/cfs:/home/data/cfs" \
-            -v "/home/data/cfs/.cache:/root/.cache" \
-            -v "/home/data/cfs/.ccache:/root/.ccache" \
-            -v "/dev/shm:/dev/shm" \
-            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
-            -v ${{ github.workspace }}:/paddle \
-            -e CI_name \
-            -e BRANCH \
-            -e PR_ID \
-            -e COMMIT_ID \
-            -e work_dir \
-            -e PADDLE_ROOT \
-            -e GIT_PR_ID \
-            -e CACHE_DIR \
-            -e CCACHE_DIR \
-            -e ci_scripts \
-            -e FLAGS_fraction_of_gpu_memory_to_use \
-            -e CTEST_PARALLEL_LEVEL \
-            -e WITH_GPU \
-            -e CUDA_ARCH_NAME \
-            -e WITH_AVX \
-            -e WITH_COVERAGE \
-            -e COVERALLS_UPLOAD \
-            -e PADDLE_VERSION \
-            -e WITH_DISTRIBUTE \
-            -e PRECISION_TEST \
-            -e WITH_PIP_CUDA_LIBRARIES \
-            -e WITH_FLAGCX \
-            -e LITE_GIT_TAG \
-            -e WITH_UNITY_BUILD \
-            -e PY_VERSION \
-            -e WITH_SHARED_PHI \
-            -e WITH_CINN \
-            -e INFERENCE_DEMO_INSTALL_DIR \
-            -e CCACHE_MAXSIZE \
-            -e CCACHE_LIMIT_MULTIPLE \
-            -e ON_INFER \
-            -e PADDLE_CUDA_INSTALL_REQUIREMENTS \
-            -e GITHUB_TOKEN \
-            -e GITHUB_API_TOKEN \
-            -e UT_RUN_TYPE_SETTING \
-            -e no_proxy \
-            -w /paddle --network host ${docker_image}
+  #   steps:
+  #     - name: Check docker image and run container
+  #       env:
+  #         CACHE_DIR: "/root/.cache/coverage"
+  #         CCACHE_DIR: "/root/.ccache/coverage"
+  #         FLAGS_fraction_of_gpu_memory_to_use: 0.15
+  #         CTEST_PARALLEL_LEVEL: 2
+  #         WITH_GPU: "ON"
+  #         CUDA_ARCH_NAME: Volta
+  #         WITH_AVX: "ON"
+  #         WITH_COVERAGE: "ON"
+  #         COVERALLS_UPLOAD: "ON"
+  #         PADDLE_VERSION: 0.0.0
+  #         CUDA_VISIBLE_DEVICES: 0,1
+  #         WITH_DISTRIBUTE: "ON"
+  #         PRECISION_TEST: "ON"
+  #         WITH_PIP_CUDA_LIBRARIES: "OFF"
+  #         WITH_FLAGCX: "ON"
+  #         LITE_GIT_TAG: develop
+  #         WITH_UNITY_BUILD: "ON"
+  #         PY_VERSION: 3.9
+  #         WITH_SHARED_PHI: "ON"
+  #         WITH_CINN: "ON"
+  #         INFERENCE_DEMO_INSTALL_DIR: /root/.cache/coverage
+  #         CCACHE_MAXSIZE: 200G
+  #         CCACHE_LIMIT_MULTIPLE: 0.8
+  #         ON_INFER: "ON"
+  #         PADDLE_CUDA_INSTALL_REQUIREMENTS: "ON"
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         UT_RUN_TYPE_SETTING: WITHOUT_HYBRID
+  #       run: |
+  #         container_name=${TASK}-build-$(date +%Y%m%d-%H%M%S)
+  #         echo "container_name=${container_name}" >> ${{ github.env }}
+  #         docker_image=${{ needs.build-docker.outputs.docker_coverage_image }}
+  #         docker run -d -t --name ${container_name} \
+  #           -v "/home/data/cfs:/home/data/cfs" \
+  #           -v "/home/data/cfs/.cache:/root/.cache" \
+  #           -v "/home/data/cfs/.ccache:/root/.ccache" \
+  #           -v "/dev/shm:/dev/shm" \
+  #           -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
+  #           -v ${{ github.workspace }}:/paddle \
+  #           -e CI_name \
+  #           -e BRANCH \
+  #           -e PR_ID \
+  #           -e COMMIT_ID \
+  #           -e work_dir \
+  #           -e PADDLE_ROOT \
+  #           -e GIT_PR_ID \
+  #           -e CACHE_DIR \
+  #           -e CCACHE_DIR \
+  #           -e ci_scripts \
+  #           -e FLAGS_fraction_of_gpu_memory_to_use \
+  #           -e CTEST_PARALLEL_LEVEL \
+  #           -e WITH_GPU \
+  #           -e CUDA_ARCH_NAME \
+  #           -e WITH_AVX \
+  #           -e WITH_COVERAGE \
+  #           -e COVERALLS_UPLOAD \
+  #           -e PADDLE_VERSION \
+  #           -e WITH_DISTRIBUTE \
+  #           -e PRECISION_TEST \
+  #           -e WITH_PIP_CUDA_LIBRARIES \
+  #           -e WITH_FLAGCX \
+  #           -e LITE_GIT_TAG \
+  #           -e WITH_UNITY_BUILD \
+  #           -e PY_VERSION \
+  #           -e WITH_SHARED_PHI \
+  #           -e WITH_CINN \
+  #           -e INFERENCE_DEMO_INSTALL_DIR \
+  #           -e CCACHE_MAXSIZE \
+  #           -e CCACHE_LIMIT_MULTIPLE \
+  #           -e ON_INFER \
+  #           -e PADDLE_CUDA_INSTALL_REQUIREMENTS \
+  #           -e GITHUB_TOKEN \
+  #           -e GITHUB_API_TOKEN \
+  #           -e UT_RUN_TYPE_SETTING \
+  #           -e no_proxy \
+  #           -w /paddle --network host ${docker_image}
 
-      - name: Download paddle.tar.gz and update test branch
-        run: |
-          docker exec -t ${{ env.container_name }}  /bin/bash -c '
-          rm -rf * .[^.]*
-          set -e
-          echo "Downloading Paddle.tar.gz"
-          wget -q --no-proxy https://paddle-github-action.bj.bcebos.com/PR/Paddle-coverage/${PR_ID}/${COMMIT_ID}/Paddle.tar.gz --no-check-certificate
-          echo "Extracting Paddle.tar.gz"
-          tar xf Paddle.tar.gz --strip-components=1
-          rm Paddle.tar.gz
-          git remote add upstream https://github.com/PaddlePaddle/Paddle.git
-          git config pull.rebase false
-          git checkout test
-          echo "Pull upstream $BRANCH"
-          source ${{ github.workspace }}/../../../proxy
-          bash ci/git_pull.sh $BRANCH
-          '
+  #     - name: Download paddle.tar.gz and update test branch
+  #       run: |
+  #         docker exec -t ${{ env.container_name }}  /bin/bash -c '
+  #         rm -rf * .[^.]*
+  #         set -e
+  #         echo "Downloading Paddle.tar.gz"
+  #         wget -q --no-proxy https://paddle-github-action.bj.bcebos.com/PR/Paddle-coverage/${PR_ID}/${COMMIT_ID}/Paddle.tar.gz --no-check-certificate
+  #         echo "Extracting Paddle.tar.gz"
+  #         tar xf Paddle.tar.gz --strip-components=1
+  #         rm Paddle.tar.gz
+  #         git remote add upstream https://github.com/PaddlePaddle/Paddle.git
+  #         git config pull.rebase false
+  #         git checkout test
+  #         echo "Pull upstream $BRANCH"
+  #         source ${{ github.workspace }}/../../../proxy
+  #         bash ci/git_pull.sh $BRANCH
+  #         '
 
-      - name: Check bypass
-        id: check-bypass
-        uses: ./.github/actions/check-bypass
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          workflow-name: coverage
+  #     - name: Check bypass
+  #       id: check-bypass
+  #       uses: ./.github/actions/check-bypass
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         workflow-name: coverage
 
-      - name: Build
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        run: |
-          docker exec -t ${{ env.container_name }}  /bin/bash -c '
-          mkdir -p /home/data/cfs/.cache/coverage
-          mkdir -p /home/data/cfs/.ccache/coverage
-          source ${{ github.workspace }}/../../../proxy
-          bash ${ci_scripts}/cmake-predownload.sh
-          bash $ci_scripts/coverage_build.sh bdist_wheel
-          '
+  #     - name: Build
+  #       if: steps.check-bypass.outputs.can-skip != 'true'
+  #       run: |
+  #         docker exec -t ${{ env.container_name }}  /bin/bash -c '
+  #         mkdir -p /home/data/cfs/.cache/coverage
+  #         mkdir -p /home/data/cfs/.ccache/coverage
+  #         source ${{ github.workspace }}/../../../proxy
+  #         bash ${ci_scripts}/cmake-predownload.sh
+  #         bash $ci_scripts/coverage_build.sh bdist_wheel
+  #         '
 
-      - name: Check added unittests
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -c '
-          source ~/.bashrc
-          source ${{ github.workspace }}/../../../proxy
-          bash $ci_scripts/check_added_ut.sh
-          '
+  #     - name: Check added unittests
+  #       if: steps.check-bypass.outputs.can-skip != 'true'
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c '
+  #         source ~/.bashrc
+  #         source ${{ github.workspace }}/../../../proxy
+  #         bash $ci_scripts/check_added_ut.sh
+  #         '
 
-      - name: Check coverage build size requires approval
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -c '
-          source ~/.bashrc
-          source ${{ github.workspace }}/../../../proxy
-          bash $ci_scripts/coverage_build_size_approval.sh
-          '
+  #     - name: Check coverage build size requires approval
+  #       if: steps.check-bypass.outputs.can-skip != 'true'
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c '
+  #         source ~/.bashrc
+  #         source ${{ github.workspace }}/../../../proxy
+  #         bash $ci_scripts/coverage_build_size_approval.sh
+  #         '
 
-      - name: Clean up env
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -c '
-          source ~/.bashrc
-          source ${ci_scripts}/utils.sh; clean_build_files
-          Build_Size=$(du -h --max-depth=0 ${work_dir}/build |awk '"'"'{print $1}'"'"')
-          echo "Build_Size=${Build_Size}" > ${work_dir}/dist/coverage_build_size
-          find ./ -type f -size +200M | xargs du -lh
-          rm -rf $(find . -name "*.a")
-          rm -rf $(find . -name "*.o")
-          rm -rf paddle_inference_install_dir
-          rm -rf paddle_inference_c_install_dir
-          rm -rf lib.linux-x86_64-3.9
-          find ./ -name "eager_generator" -or -name  "kernel_signature_generator" -or -name "eager_legacy_op_function_generator" | xargs rm -rf
-          rm -rf ./python/build/lib.linux-x86_64-3.9/
-          cd "${work_dir}/build/third_party" && find $(ls | grep -v "dlpack" | grep -v "install" | grep -v "eigen3" | grep -v "gflags") -type f ! -name "*.so" -a ! -name "libdnnl.so*" -delete
-          cd /
-          tar --use-compress-program="pzstd -1" -cf Paddle.tar.gz paddle
-          '
+  #     - name: Clean up env
+  #       if: steps.check-bypass.outputs.can-skip != 'true'
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c '
+  #         source ~/.bashrc
+  #         source ${ci_scripts}/utils.sh; clean_build_files
+  #         Build_Size=$(du -h --max-depth=0 ${work_dir}/build |awk '"'"'{print $1}'"'"')
+  #         echo "Build_Size=${Build_Size}" > ${work_dir}/dist/coverage_build_size
+  #         find ./ -type f -size +200M | xargs du -lh
+  #         rm -rf $(find . -name "*.a")
+  #         rm -rf $(find . -name "*.o")
+  #         rm -rf paddle_inference_install_dir
+  #         rm -rf paddle_inference_c_install_dir
+  #         rm -rf lib.linux-x86_64-3.9
+  #         find ./ -name "eager_generator" -or -name  "kernel_signature_generator" -or -name "eager_legacy_op_function_generator" | xargs rm -rf
+  #         rm -rf ./python/build/lib.linux-x86_64-3.9/
+  #         cd "${work_dir}/build/third_party" && find $(ls | grep -v "dlpack" | grep -v "install" | grep -v "eigen3" | grep -v "gflags") -type f ! -name "*.so" -a ! -name "libdnnl.so*" -delete
+  #         cd /
+  #         tar --use-compress-program="pzstd -1" -cf Paddle.tar.gz paddle
+  #         '
 
-      - name: Upload coverage product
-        if: steps.check-bypass.outputs.can-skip != 'true'
-        env:
-          home_path: ${{ github.workspace }}/..
-          bos_file: ${{ github.workspace }}/../bos_retry/BosClient.py
-          paddle_whl: paddlepaddle_gpu-0.0.0-cp39-cp39-linux_x86_64.whl
-        run: |
-          docker exec -t ${{ env.container_name }} /bin/bash -c '
-          echo "::group::Install bce-python-sdk"
-          source ${{ github.workspace }}/../../../proxy
-          python -m pip install bce-python-sdk==0.8.74
-          echo "::endgroup::"
-          export AK=paddle
-          export SK=paddle
-          if [ ! -f "${{ env.bos_file }}" ]; then
-            wget -q --no-proxy -O ${{ env.home_path }}/bos_retry.tar.gz https://xly-devops.bj.bcebos.com/home/bos_retry.tar.gz --no-check-certificate
-            mkdir ${{ env.home_path }}/bos_retry
-            tar xf ${{ env.home_path }}/bos_retry.tar.gz -C ${{ env.home_path }}/bos_retry
-          fi
-          cd /paddle/dist
-          echo "Uploading coverage build size"
-          python ${{ env.bos_file }} coverage_build_size paddle-github-action/PR/coverage/${{ env.PR_ID }}/${{ env.COMMIT_ID }}
-          echo "Uploading coverage wheel"
-          python ${{ env.bos_file }} ${{ env.paddle_whl }} paddle-github-action/PR/coverage/${{ env.PR_ID }}/${{ env.COMMIT_ID }}
-          cd /
-          echo "Uploading Paddle.tar.gz"
-          python ${{ env.bos_file }} Paddle.tar.gz paddle-github-action/PR/coverage/${{ env.PR_ID }}/${{ env.COMMIT_ID }}
-          rm Paddle.tar.gz
-          '
+  #     - name: Upload coverage product
+  #       if: steps.check-bypass.outputs.can-skip != 'true'
+  #       env:
+  #         home_path: ${{ github.workspace }}/..
+  #         bos_file: ${{ github.workspace }}/../bos_retry/BosClient.py
+  #         paddle_whl: paddlepaddle_gpu-0.0.0-cp39-cp39-linux_x86_64.whl
+  #       run: |
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c '
+  #         echo "::group::Install bce-python-sdk"
+  #         source ${{ github.workspace }}/../../../proxy
+  #         python -m pip install bce-python-sdk==0.8.74
+  #         echo "::endgroup::"
+  #         export AK=paddle
+  #         export SK=paddle
+  #         if [ ! -f "${{ env.bos_file }}" ]; then
+  #           wget -q --no-proxy -O ${{ env.home_path }}/bos_retry.tar.gz https://xly-devops.bj.bcebos.com/home/bos_retry.tar.gz --no-check-certificate
+  #           mkdir ${{ env.home_path }}/bos_retry
+  #           tar xf ${{ env.home_path }}/bos_retry.tar.gz -C ${{ env.home_path }}/bos_retry
+  #         fi
+  #         cd /paddle/dist
+  #         echo "Uploading coverage build size"
+  #         python ${{ env.bos_file }} coverage_build_size paddle-github-action/PR/coverage/${{ env.PR_ID }}/${{ env.COMMIT_ID }}
+  #         echo "Uploading coverage wheel"
+  #         python ${{ env.bos_file }} ${{ env.paddle_whl }} paddle-github-action/PR/coverage/${{ env.PR_ID }}/${{ env.COMMIT_ID }}
+  #         cd /
+  #         echo "Uploading Paddle.tar.gz"
+  #         python ${{ env.bos_file }} Paddle.tar.gz paddle-github-action/PR/coverage/${{ env.PR_ID }}/${{ env.COMMIT_ID }}
+  #         rm Paddle.tar.gz
+  #         '
 
-      - name: Terminate and delete the container
-        if: ${{ steps.check-bypass.outputs.can-skip != 'true' && always() }}
-        run: |
-          set +e
-          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
-          docker stop ${{ env.container_name }}
-          docker rm ${{ env.container_name }}
+  #     - name: Terminate and delete the container
+  #       if: ${{ steps.check-bypass.outputs.can-skip != 'true' && always() }}
+  #       run: |
+  #         set +e
+  #         docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
+  #         docker stop ${{ env.container_name }}
+  #         docker rm ${{ env.container_name }}
 
 
   test:
     name: Coverage test
-    needs: [build, build-docker]
-    if: needs.build.outputs.can-skip != 'true'
+    needs: [build-docker]
+    # if: needs.build.outputs.can-skip != 'true'
     runs-on:
       group: BD_BJ-V100
     steps:
@@ -331,7 +331,7 @@ jobs:
           rm -rf * .[^.]*
           set -e
           echo "Downloading Paddle.tar.gz"
-          wget -q --no-proxy https://paddle-github-action.bj.bcebos.com/PR/coverage/${PR_ID}/${COMMIT_ID}/Paddle.tar.gz --no-check-certificate
+          https://paddle-github-action.bj.bcebos.com/PR/coverage/73481/3e1c438c236b5a8e36279cc3bee6d98a4eb9e8b9/Paddle.tar.gz
           echo "Extracting Paddle.tar.gz"
           tar --use-compress-program="pzstd -1" -xf Paddle.tar.gz --strip-components=1
           rm Paddle.tar.gz
@@ -385,11 +385,11 @@ jobs:
           fi
           '
 
-      - name: Terminate and delete the container
-        if: always()
-        run: |
-          set +e
-          rm Paddle.tar.gz
-          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
-          docker stop ${{ env.container_name }}
-          docker rm ${{ env.container_name }}
+    # - name: Terminate and delete the container
+    #   if: always()
+    #   run: |
+    #     set +e
+    #     rm Paddle.tar.gz
+    #     docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
+    #     docker stop ${{ env.container_name }}
+    #     docker rm ${{ env.container_name }}
